engines:
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
  fixme:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "unusedcode,cleancode"
    checks:
      CleanCode/StaticAccess:
        enabled: false
  method-lines:
    enabled: false
  file-lines:
    enabled: false
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- "tests/"
- "sample-data/"
- "i18n/"
- "bin/"
- "languages/"
- "includes/classes/legacy/"
- "vendor/"