language: php
dist: focal

services:
    - mysql

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

env:
  - WP_VERSION=latest

matrix:
  fast_finish: true
  include:
    - name: Coding Standards
      php: 7.4
      env: WP_VERSION=latest RUN_PHPCS=1
    - name: Bleeding Edge
      php: nightly
      env: WP_VERSION=trunk
  allow_failures:
    - name: Bleeding Edge

before_install:
  - phpenv config-rm xdebug.ini || true

before_script:
  - composer require  wp-coding-standards/wpcs dealerdirect/phpcodesniffer-composer-installer --update-with-all-dependencies

script:
  - ./vendor/bin/phpcs --colors -p -s -v -n --standard=./.phpcs.xml